name: doc release

on:
  version:
    required: true
    description: "version to release"
jobs:
  release-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm ci && npm run docs:build
      - name: Release Doc
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .vitepress/dist # The folder the action should deploy.